require:
- rubocop-rake
- rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/NestedGroups:
  Max: 4
